"""Reporting helpers for Veridian Quant v2."""

from veridian_quant.v2.reporting.context import (
    R_CONTEXT_BUCKET_COLUMNS,
    TRADE_SIGNAL_CONTEXT_COLUMNS,
    build_r_by_atr_stretch_context_rows,
    build_r_by_consecutive_down_closes_rows,
    build_r_by_drawdown_depth_context_rows,
    build_r_by_fresh_low_context_rows,
    build_r_by_nifty_trend_context_rows,
    build_r_by_pre_signal_return_context_rows,
    build_r_by_relative_strength_context_rows,
    build_r_by_signal_candle_context_rows,
    build_r_by_stock_trend_context_rows,
    build_r_by_zscore_depth_rows,
    build_trade_signal_context_rows,
)
from veridian_quant.v2.reporting.diagnostics import (
    EXIT_REASON_SUMMARY_COLUMNS,
    REJECTION_SUMMARY_COLUMNS,
    R_MULTIPLE_BY_EXIT_REASON_COLUMNS,
    R_MULTIPLE_BY_SYMBOL_COLUMNS,
    R_MULTIPLE_BY_SYMBOL_YEAR_COLUMNS,
    R_MULTIPLE_BY_YEAR_COLUMNS,
    R_MULTIPLE_SUMMARY_COLUMNS,
    SYMBOL_SUMMARY_COLUMNS,
    YEARLY_SUMMARY_COLUMNS,
    build_exit_reason_summary_rows,
    build_r_multiple_by_exit_reason_rows,
    build_r_multiple_by_symbol_rows,
    build_r_multiple_by_symbol_year_rows,
    build_r_multiple_by_year_rows,
    build_r_multiple_summary_rows,
    build_rejection_summary_rows,
    build_symbol_summary_rows,
    build_yearly_summary_rows,
)
from veridian_quant.v2.reporting.exporters import export_portfolio_backtest_csvs
from veridian_quant.v2.reporting.filter_simulation import (
    CANDIDATE_FILTER_SIMULATION_BY_SYMBOL_COLUMNS,
    CANDIDATE_FILTER_SIMULATION_BY_YEAR_COLUMNS,
    CANDIDATE_FILTER_SIMULATION_COLUMNS,
    CANDIDATE_FILTER_SIMULATION_REJECTED_TRADES_COLUMNS,
    build_candidate_filter_simulation_by_symbol_rows,
    build_candidate_filter_simulation_by_year_rows,
    build_candidate_filter_simulation_rejected_trade_rows,
    build_candidate_filter_simulation_rows,
)
from veridian_quant.v2.reporting.metrics import (
    PerformanceSummary,
    calculate_performance_summary,
)
from veridian_quant.v2.reporting.progress import (
    NullProgressReporter,
    ProgressReporter,
)

__all__ = [
    "EXIT_REASON_SUMMARY_COLUMNS",
    "NullProgressReporter",
    "PerformanceSummary",
    "ProgressReporter",
    "R_CONTEXT_BUCKET_COLUMNS",
    "REJECTION_SUMMARY_COLUMNS",
    "R_MULTIPLE_BY_EXIT_REASON_COLUMNS",
    "R_MULTIPLE_BY_SYMBOL_COLUMNS",
    "R_MULTIPLE_BY_SYMBOL_YEAR_COLUMNS",
    "R_MULTIPLE_BY_YEAR_COLUMNS",
    "R_MULTIPLE_SUMMARY_COLUMNS",
    "SYMBOL_SUMMARY_COLUMNS",
    "TRADE_SIGNAL_CONTEXT_COLUMNS",
    "YEARLY_SUMMARY_COLUMNS",
    "build_r_by_nifty_trend_context_rows",
    "build_r_by_atr_stretch_context_rows",
    "build_r_by_consecutive_down_closes_rows",
    "build_r_by_drawdown_depth_context_rows",
    "build_r_by_fresh_low_context_rows",
    "build_r_by_pre_signal_return_context_rows",
    "build_r_by_relative_strength_context_rows",
    "build_r_by_signal_candle_context_rows",
    "build_r_by_stock_trend_context_rows",
    "build_r_by_zscore_depth_rows",
    "build_trade_signal_context_rows",
    "CANDIDATE_FILTER_SIMULATION_BY_SYMBOL_COLUMNS",
    "CANDIDATE_FILTER_SIMULATION_BY_YEAR_COLUMNS",
    "CANDIDATE_FILTER_SIMULATION_COLUMNS",
    "CANDIDATE_FILTER_SIMULATION_REJECTED_TRADES_COLUMNS",
    "build_candidate_filter_simulation_by_symbol_rows",
    "build_candidate_filter_simulation_by_year_rows",
    "build_candidate_filter_simulation_rejected_trade_rows",
    "build_candidate_filter_simulation_rows",
    "calculate_performance_summary",
    "build_exit_reason_summary_rows",
    "build_r_multiple_by_exit_reason_rows",
    "build_r_multiple_by_symbol_rows",
    "build_r_multiple_by_symbol_year_rows",
    "build_r_multiple_by_year_rows",
    "build_r_multiple_summary_rows",
    "build_rejection_summary_rows",
    "build_symbol_summary_rows",
    "build_yearly_summary_rows",
    "export_portfolio_backtest_csvs",
]
